//trigger github action
# Basic Jekyll Configuration for Microsoft Certified AI Engineer

# Site settings
title: AI-102 Study Journey
email: nolanaug@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A personal study journey and public resource hub for the Microsoft AI-102 Certification.
baseurl: "/Microsoft-Certified-AI-Engineer" # the subpath of your site, e.g. /blog. If hosted at root, leave empty.
url: "https://m-indsRefuge.github.io" # the base hostname & protocol for your site
github_username: m-indsRefuge

# Define collections for structured content like weekly summaries
collections:
  weeks:
    output: true
    permalink: /weeks/:path/

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
# exclude:
#   - Gemfile
#   - Gemfile.lock
